### ISSUE TITLE
How do code find blockchain?

### ISSUE THREAD

**Issue by jonspock** [mulllhausen/btc-inquisitor#1]
Traceback (most recent call last):
  File "./btc-inquisitor.py", line 47, in <module>
    btc_grunt.init_base_dir()
  File "/Users/Extra/btc-inquisitor/btc_grunt.py", line 411, in init_base_dir
    if not os.path.exists(base_dir):
NameError: global name 'base_dir' is not defined

I get this when I run unit_tests.sh

**Comment by mulllhausen** [comment]
Hi jonspock, I'm going through a big restructuring of this project at the moment. The unit tests will not pass as you say. Previously I was storing transaction metadata in text files under a directory structure (my thinking was to make all metadata easily visible to the user) however it got too inefficient to be practical so I am switching to a mysql database. Stay tuned though, since all major functionality is working, its just not neatly integrated back into the btc-inquisitor.py script yet.

For example `./get_block.py 1 full-json` will work (you need to have bitcoin-cli installed and your config.json configured). Also `./get_tx.py 100000-1` will work too.
